### ISSUE TITLE
Windows encoding issue

### ISSUE THREAD

**Issue by tomasara413** [InitialPosition/pyJAMa#2]
Windows expects the default encoding of files to be cp1250 - since this is not the encoding used, it causes pyJAMa to crash on start with the following error traceback:

> File "I:\Users\tomasara413\Downloads\pyJAMa\main.py", line 178, in <module>
    main_menu()
  File "I:\Users\tomasara413\Downloads\pyJAMa\main.py", line 27, in main_menu
    print_file('files/logo.txt')
  File "I:\Users\tomasara413\Downloads\pyJAMa\util\ConsoleFunctions.py", line 12, in print_file
    for line in f.read().splitlines():
  File "I:\Python\Python39\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 112: character maps to <undefined>

In order to fix this, encoding of the files should be specified when opening them. Adjusting the following `open(file, 'r')` in ConsoleFunctions.py to `open(file, 'r', encoding="utf8")` will work.

**Comment by InitialPosition** [comment]
Noted. I always forget to specify text file encoding when working in python 😄 
Will push a fix in about 30 minutes.

**Comment by InitialPosition** [comment]
Issue fixed in Version 1.3.1.
